from .models import (
    BestPractice,
    DocumentationSource,
    Framework,
    SourceAuthority,
    SourceCategory,
    TrainingDomain,
    TrainingTechnique,
)

CURATED_SOURCES: list[DocumentationSource] = [
    # === Official Documentation ===
    DocumentationSource(
        name="Hugging Face Transformers Docs",
        url="https://huggingface.co/docs/transformers/index",
        category=SourceCategory.documentation,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal, TrainingDomain.speech],
        techniques=[TrainingTechnique.lora, TrainingTechnique.qlora, TrainingTechnique.full_fine_tuning, TrainingTechnique.prompt_tuning, TrainingTechnique.prefix_tuning, TrainingTechnique.p_tuning],
        frameworks=[Framework.transformers, Framework.peft, Framework.trl, Framework.accelerate],
        description="Official Hugging Face Transformers library documentation with training guides, SFT, DPOTrainer, and PEFT integration.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="PEFT Documentation",
        url="https://huggingface.co/docs/peft/index",
        category=SourceCategory.documentation,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal],
        techniques=[TrainingTechnique.lora, TrainingTechnique.qlora, TrainingTechnique.dora, TrainingTechnique.rs_lora, TrainingTechnique.adapter, TrainingTechnique.prompt_tuning, TrainingTechnique.prefix_tuning, TrainingTechnique.p_tuning],
        frameworks=[Framework.peft],
        description="Parameter-Efficient Fine-Tuning: LoRA, QLoRA, DoRA, IA3, AdaLoRA, and prompt tuning methods.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Unsloth Documentation",
        url="https://docs.unsloth.ai/",
        category=SourceCategory.documentation,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.llm],
        techniques=[TrainingTechnique.lora, TrainingTechnique.qlora],
        frameworks=[Framework.unsloth],
        description="Unsloth: 2x faster LLM fine-tuning with optimized kernels, reduced memory usage, and manual quantization.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Axolotl Documentation",
        url="https://axolotl.ai/docs/",
        category=SourceCategory.documentation,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.llm],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.lora, TrainingTechnique.qlora],
        frameworks=[Framework.axolotl],
        description="Axolotl: streamlined fine-tuning framework supporting full-parameter and LoRA training for open-source LLMs.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="PyTorch Training Docs",
        url="https://pytorch.org/docs/stable/index.html",
        category=SourceCategory.documentation,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal, TrainingDomain.reinforcement_learning, TrainingDomain.diffusion, TrainingDomain.speech, TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.distillation, TrainingTechnique.curriculum_learning, TrainingTechnique.self_supervised, TrainingTechnique.contrastive],
        frameworks=[Framework.pytorch],
        description="Official PyTorch documentation with distributed training, FSDP, torch.compile, and performance optimization guides.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="TensorFlow Training Guide",
        url="https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch",
        category=SourceCategory.documentation,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning],
        frameworks=[Framework.tensorflow],
        description="TensorFlow official training guides including custom training loops, distribution strategies, and TFRecord pipelines.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="DeepSpeed Documentation",
        url="https://www.deepspeed.ai/docs/",
        category=SourceCategory.documentation,
        authority=SourceAuthority.research_lab,
        domains=[TrainingDomain.llm, TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.lora],
        frameworks=[Framework.deepspeed],
        description="Microsoft DeepSpeed: ZeRO optimization, DeepSpeed MoE, and Megatron-LM integration for large-scale training.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="JAX Training Docs",
        url="https://jax.readthedocs.io/en/latest/",
        category=SourceCategory.documentation,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.self_supervised],
        frameworks=[Framework.jax, Framework.flax],
        description="JAX: accelerated numerical computing with just-in-time compilation, automatic differentiation, and pmap/shard_map for distributed training.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="MLX Documentation",
        url="https://ml-explore.github.io/mlx/build/html/index.html",
        category=SourceCategory.documentation,
        authority=SourceAuthority.research_lab,
        domains=[TrainingDomain.llm, TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.lora, TrainingTechnique.qlora],
        frameworks=[Framework.mlx],
        description="Apple MLX: efficient machine learning framework for Apple Silicon with unified memory architecture and on-device fine-tuning.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="vLLM Documentation",
        url="https://docs.vllm.ai/",
        category=SourceCategory.documentation,
        authority=SourceAuthority.research_lab,
        domains=[TrainingDomain.llm],
        frameworks=[Framework.vllm],
        description="vLLM: high-throughput LLM serving with PagedAttention, continuous batching, and online model updates.",
        last_verified="2026-07-11",
    ),
    # === Papers & Research ===
    DocumentationSource(
        name="arXiv (cs.LG, cs.CL, cs.CV)",
        url="https://arxiv.org/",
        category=SourceCategory.paper,
        authority=SourceAuthority.academic,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal, TrainingDomain.general],
        description="Preprint server for cutting-edge ML research papers on training techniques, continual learning, and model optimization.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Papers with Code",
        url="https://paperswithcode.com/",
        category=SourceCategory.benchmark,
        authority=SourceAuthority.academic,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal, TrainingDomain.general],
        description="Curated papers with code implementations, benchmarks, and state-of-the-art results for training methodologies.",
        last_verified="2026-07-11",
    ),
    # === Repositories ===
    DocumentationSource(
        name="GitHub Trending ML",
        url="https://github.com/topics/machine-learning",
        category=SourceCategory.repository,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.general],
        description="GitHub repositories for training frameworks, fine-tuning tools, and ML infrastructure.",
        last_verified="2026-07-11",
    ),
    # === Community & Discussions ===
    DocumentationSource(
        name="Hugging Face Community",
        url="https://discuss.huggingface.co/",
        category=SourceCategory.discussion,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.multimodal, TrainingDomain.speech],
        description="Community discussions on training recipes, hardware requirements, dataset preparation, and troubleshooting.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Reddit r/MachineLearning",
        url="https://www.reddit.com/r/MachineLearning/",
        category=SourceCategory.discussion,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.general],
        description="Active community discussions on training techniques, framework comparisons, hardware benchmarks, and best practices.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Stack Overflow (training)",
        url="https://stackoverflow.com/questions/tagged/machine-learning",
        category=SourceCategory.discussion,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.general],
        description="Q&A for training pipelines, debugging training issues, and implementation patterns.",
        last_verified="2026-07-11",
    ),
    # === Blogs ===
    DocumentationSource(
        name="Lil'Log (Lilian Weng)",
        url="https://lilianweng.github.io/",
        category=SourceCategory.blog,
        authority=SourceAuthority.research_lab,
        domains=[TrainingDomain.llm, TrainingDomain.reinforcement_learning, TrainingDomain.general],
        techniques=[TrainingTechnique.continual_pretraining, TrainingTechnique.contrastive, TrainingTechnique.distillation],
        description="In-depth blog posts on LLM training, RLHF, prompt engineering, and continual learning from OpenAI researcher.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Sebastian Raschka Blog",
        url="https://sebastianraschka.com/blog/",
        category=SourceCategory.blog,
        authority=SourceAuthority.academic,
        domains=[TrainingDomain.llm, TrainingDomain.vision, TrainingDomain.general],
        techniques=[TrainingTechnique.lora, TrainingTechnique.qlora, TrainingTechnique.full_fine_tuning],
        description="Practical guides on LLM fine-tuning, PEFT methods, and PyTorch best practices from a leading ML educator.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="The Gradient",
        url="https://thegradient.pub/",
        category=SourceCategory.blog,
        authority=SourceAuthority.community,
        domains=[TrainingDomain.llm, TrainingDomain.general],
        description="Long-form essays on ML research trends, training methodology analysis, and critical perspectives.",
        last_verified="2026-07-11",
    ),
    # === Courses ===
    DocumentationSource(
        name="Fast.ai Practical Deep Learning",
        url="https://course.fast.ai/",
        category=SourceCategory.course,
        authority=SourceAuthority.academic,
        domains=[TrainingDomain.general],
        techniques=[TrainingTechnique.full_fine_tuning],
        frameworks=[Framework.pytorch],
        description="Practical deep learning course covering training from scratch, fine-tuning, and deployment with PyTorch.",
        last_verified="2026-07-11",
    ),
    DocumentationSource(
        name="Hugging Face NLP Course",
        url="https://huggingface.co/learn/nlp-course/",
        category=SourceCategory.course,
        authority=SourceAuthority.official,
        domains=[TrainingDomain.llm],
        techniques=[TrainingTechnique.full_fine_tuning, TrainingTechnique.lora],
        frameworks=[Framework.transformers, Framework.peft],
        description="Comprehensive NLP course with hands-on training exercises using Hugging Face ecosystem.",
        last_verified="2026-07-11",
    ),
]

BEST_PRACTICES: list[BestPractice] = [
    BestPractice(
        id="bp-001",
        title="Prefer PEFT methods for domain adaptation",
        description="Use LoRA/QLoRA instead of full fine-tuning when adapting large models to specific domains. PEFT preserves base model capabilities, reduces catastrophic forgetting, and enables cost-effective iteration.",
        domain=TrainingDomain.llm,
        technique=TrainingTechnique.lora,
        priority=1,
        evidence_urls=[
            "https://huggingface.co/docs/peft/index",
            "https://arxiv.org/abs/2106.09685",
        ],
        tags=["peft", "efficiency", "domain-adaptation"],
    ),
    BestPractice(
        id="bp-002",
        title="Use gradient checkpointing and mixed precision",
        description="Enable gradient checkpointing (activation recomputation) and mixed precision training (bf16/fp16) to reduce memory footprint by up to 50% while maintaining model quality.",
        domain=TrainingDomain.general,
        priority=1,
        evidence_urls=[
            "https://pytorch.org/docs/stable/notes/amp_examples.html",
            "https://huggingface.co/docs/transformers/perf_train_gpu_one",
        ],
        tags=["memory", "performance", "mixed-precision"],
    ),
    BestPractice(
        id="bp-003",
        title="Implement continuous evaluation during training",
        description="Run evaluation on a held-out validation set at regular intervals during training. Monitor for overfitting, catastrophic forgetting, and distribution shift. Use early stopping with patience.",
        domain=TrainingDomain.general,
        priority=1,
        evidence_urls=[
            "https://pytorch.org/tutorials/beginner/introyt/trainingyt.html",
        ],
        tags=["evaluation", "monitoring", "validation"],
    ),
    BestPractice(
        id="bp-004",
        title="Version datasets and model checkpoints",
        description="Use DVC, Hugging Face Datasets versioning, or Git LFS to track dataset versions. Save checkpoints with optimizer state, learning rate scheduler state, and evaluation metrics for reproducibility.",
        domain=TrainingDomain.general,
        priority=1,
        evidence_urls=[
            "https://dvc.org/doc/start/data-management/data-versioning",
            "https://huggingface.co/docs/datasets/v2.0.0/en/loading#slice-splits",
        ],
        tags=["reproducibility", "versioning", "mlops"],
    ),
    BestPractice(
        id="bp-005",
        title="Use learning rate warmup and cosine decay",
        description="Apply linear warmup for the initial steps followed by cosine annealing schedule. This stabilizes training in early steps and improves convergence quality across domains.",
        domain=TrainingDomain.general,
        priority=2,
        evidence_urls=[
            "https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.CosineAnnealingLR",
            "https://arxiv.org/abs/1812.01187",
        ],
        tags=["learning-rate", "scheduler", "convergence"],
    ),
    BestPractice(
        id="bp-006",
        title="Maintain a data quality pipeline",
        description="Implement deduplication, contamination checks, PII filtering, and format validation. High-quality training data is the single most important factor for model performance.",
        domain=TrainingDomain.general,
        priority=1,
        evidence_urls=[
            "https://huggingface.co/spaces/datasets-quality/quality-checker",
        ],
        tags=["data-quality", "preprocessing", "curation"],
    ),
    BestPractice(
        id="bp-007",
        title="Apply curriculum learning for complex tasks",
        description="Structure training data from simple to complex examples. For LLMs: start with shorter sequences, then progress to longer contexts. For vision: begin with clean data, add augmentations progressively.",
        domain=TrainingDomain.general,
        technique=TrainingTechnique.curriculum_learning,
        priority=3,
        evidence_urls=[
            "https://arxiv.org/abs/2103.09859",
        ],
        tags=["curriculum", "training-strategy"],
    ),
    BestPractice(
        id="bp-008",
        title="Use distributed strategies appropriate to scale",
        description="For single-node multi-GPU: DDP. For multi-node: FSDP or DeepSpeed ZeRO stages 2/3. For extremely large models: pipeline parallelism + tensor parallelism + data parallelism.",
        domain=TrainingDomain.general,
        priority=1,
        evidence_urls=[
            "https://pytorch.org/docs/stable/distributed.html",
            "https://www.deepspeed.ai/tutorials/zero/",
        ],
        tags=["distributed", "scalability", "fsdp", "deepspeed"],
    ),
    BestPractice(
        id="bp-009",
        title="Monitor for loss spikes and NaN gradients",
        description="Detect loss spikes early with gradient clipping (max_norm=1.0), loss NaN detection, and automatic training suspension. Log gradient norms per layer for debugging.",
        domain=TrainingDomain.general,
        priority=2,
        evidence_urls=[
            "https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html",
        ],
        tags=["stability", "monitoring", "debugging"],
    ),
    BestPractice(
        id="bp-010",
        title="Implement rehearsal-based continual learning",
        description="Maintain a small rehearsal buffer of representative past examples to replay during continual training. Combine with EWC or SI regularization to prevent catastrophic forgetting.",
        domain=TrainingDomain.llm,
        technique=TrainingTechnique.rehearsal,
        priority=2,
        evidence_urls=[
            "https://arxiv.org/abs/1902.08630",
        ],
        tags=["continual-learning", "forgetting", "rehearsal"],
    ),
    BestPractice(
        id="bp-011",
        title="Benchmark hardware before production training",
        description="Profile throughput (tokens/second), memory utilization, and scaling efficiency on target hardware. Use small test runs to determine optimal batch size, sequence length, and gradient accumulation steps.",
        domain=TrainingDomain.general,
        priority=2,
        evidence_urls=[
            "https://huggingface.co/docs/transformers/perf_train_gpu_one",
        ],
        tags=["hardware", "benchmarking", "profiling"],
    ),
    BestPractice(
        id="bp-012",
        title="Track training experiments with MLflow or W&B",
        description="Log hyperparameters, metrics, checkpoints, and configuration for every run. Enable experiment comparison, reproducibility, and regression detection across training iterations.",
        domain=TrainingDomain.general,
        priority=2,
        evidence_urls=[
            "https://mlflow.org/docs/latest/deep-learning/index.html",
            "https://docs.wandb.ai/guides/track",
        ],
        tags=["experiment-tracking", "mlops", "observability"],
    ),
    BestPractice(
        id="bp-013",
        title="Use adapter fusion for multi-task continual training",
        description="Train separate adapters for each task or domain, then fuse them during inference. Enables scalable continual learning without catastrophic forgetting.",
        domain=TrainingDomain.llm,
        technique=TrainingTechnique.adapter,
        priority=3,
        evidence_urls=[
            "https://arxiv.org/abs/1905.10676",
        ],
        tags=["adapters", "multi-task", "continual-learning"],
    ),
    BestPractice(
        id="bp-014",
        title="Validate with multiple checkpoints, not just final",
        description="Evaluate intermediate checkpoints to find the best-performing model. The final checkpoint is often not the optimal one due to convergence dynamics.",
        domain=TrainingDomain.general,
        priority=2,
        evidence_urls=[],
        tags=["evaluation", "checkpoints", "model-selection"],
    ),
    BestPractice(
        id="bp-015",
        title="Quantize after training for production deployment",
        description="Apply GPTQ, AWQ, or GGUF quantization after fine-tuning to reduce model size 2-4x with minimal quality loss. For on-device deployment, consider QLoRA-style quantization-aware training.",
        domain=TrainingDomain.llm,
        technique=TrainingTechnique.quantization_aware,
        priority=2,
        evidence_urls=[
            "https://arxiv.org/abs/2210.17323",
            "https://github.com/IST-DASLab/gptq",
        ],
        tags=["quantization", "deployment", "optimization"],
    ),
]


def source_registry() -> list[dict]:
    return [s.model_dump() for s in CURATED_SOURCES]


def best_practices_catalog() -> list[dict]:
    return [bp.model_dump() for bp in BEST_PRACTICES]


def source_screening_policy() -> list[str]:
    return [
        "Prefer official documentation over third-party summaries.",
        "Always capture URL, retrieval date, and source authority.",
        "Respect robots.txt, rate limits, and terms of service.",
        "Never scrape access-controlled or authentication-gated content.",
        "Preserve version information for documentation sources.",
        "Cross-reference information across at least 2 independent sources.",
        "Flag deprecated or archived documentation clearly.",
        "Cache results to reduce redundant network requests.",
    ]
