import type {
  JudgeReport,
  ExecutionContext,
  PermissionDecision,
  ToolCallRecord,
  EvidenceRecord
} from "./types.js";

export class ReportWriter {
  writeJudgeReport(report: JudgeReport): string {
    const lines: string[] = [];
    lines.push("# Judge Report");
    lines.push("");
    lines.push(`- **Execution ID:** ${report.executionId}`);
    lines.push(`- **Verdict:** ${report.verdict}`);
    lines.push(`- **Score:** ${report.score.toFixed(1)} / ${report.minScore}`);
    lines.push(`- **Timestamp:** ${report.timestamp}`);
    lines.push("");
    lines.push("## Summary");
    lines.push("");
    lines.push(report.summary);
    lines.push("");
    lines.push("## Evidence Reviewed");
    lines.push("");
    lines.push(`- **Total evidence records:** ${report.evidenceReviewed}`);
    lines.push("");
    lines.push("## Failures");
    lines.push("");
    if (report.failures.length === 0) {
      lines.push("_No failures detected._");
    } else {
      for (const f of report.failures) {
        lines.push(`- ❌ ${f}`);
      }
    }
    lines.push("");
    lines.push("## Risks");
    lines.push("");
    if (report.risks.length === 0) {
      lines.push("_No risks identified._");
    } else {
      for (const r of report.risks) {
        lines.push(`- ⚠️ ${r}`);
      }
    }
    lines.push("");
    lines.push("## Files Affected");
    lines.push("");
    if (report.filesAffected.length === 0) {
      lines.push("_No files affected._");
    } else {
      for (const f of report.filesAffected) {
        lines.push(`- \`${f}\``);
      }
    }
    lines.push("");
    lines.push("## Tests Executed");
    lines.push("");
    lines.push(`- **Count:** ${report.testsExecuted}`);
    lines.push("");
    lines.push("## Required Next Steps");
    lines.push("");
    if (report.requiredNextSteps.length === 0) {
      lines.push("_No required next steps._");
    } else {
      for (const step of report.requiredNextSteps) {
        lines.push(`- ${step}`);
      }
    }
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("_Generated by AEOS Deterministic Judge v0.1_");
    return lines.join("\n");
  }

  writeExecutionSummary(ctx: ExecutionContext): string {
    const lines: string[] = [];
    lines.push("# Execution Summary");
    lines.push("");
    lines.push(`- **Execution ID:** ${ctx.executionId}`);
    lines.push(`- **Playbook:** ${ctx.playbookId}`);
    lines.push(`- **Target:** ${ctx.targetPath}`);
    lines.push(`- **Status:** ${ctx.status}`);
    lines.push(`- **Started:** ${ctx.startedAt}`);
    lines.push(`- **Completed:** ${ctx.completedAt ?? "N/A"}`);
    if (ctx.error) lines.push(`- **Error:** ${ctx.error}`);
    lines.push("");
    lines.push("## Resolved Playbook");
    lines.push("");
    if (ctx.resolvedPlaybook) {
      lines.push(`- **ID:** ${ctx.resolvedPlaybook.id}`);
      lines.push(`- **Name:** ${ctx.resolvedPlaybook.name}`);
      lines.push(`- **Risk Level:** ${ctx.resolvedPlaybook.risk_level}`);
    }
    lines.push("");
    lines.push("## Resolved Skills");
    lines.push("");
    if (ctx.resolvedSkills.length === 0) {
      lines.push("_No skills resolved._");
    } else {
      for (const sk of ctx.resolvedSkills) {
        lines.push(`- ${sk.id} (v${sk.version})`);
      }
    }
    lines.push("");
    lines.push("## Resolved MCPs");
    lines.push("");
    if (ctx.resolvedMCPs.length === 0) {
      lines.push("_No MCPs resolved._");
    } else {
      for (const mcp of ctx.resolvedMCPs) {
        lines.push(`- ${mcp.id} (${mcp.type})`);
      }
    }
    lines.push("");
    lines.push("## Resolved LCPs");
    lines.push("");
    if (ctx.resolvedLCPs.length === 0) {
      lines.push("_No LCPs resolved._");
    } else {
      for (const lcp of ctx.resolvedLCPs) {
        lines.push(`- ${lcp.id} (priority: ${lcp.priority})`);
      }
    }
    lines.push("");
    lines.push("## Agent");
    lines.push("");
    if (ctx.agent) {
      lines.push(`- **ID:** ${ctx.agent.id}`);
      lines.push(`- **Role:** ${ctx.agent.role}`);
    }
    lines.push("");
    lines.push("## Permission Decisions");
    lines.push("");
    const denied = ctx.permissionDecisions.filter((d) => !d.allowed);
    const allowed = ctx.permissionDecisions.filter((d) => d.allowed);
    lines.push(`- **Total decisions:** ${ctx.permissionDecisions.length}`);
    lines.push(`- **Allowed:** ${allowed.length}`);
    lines.push(`- **Denied:** ${denied.length}`);
    lines.push("");
    lines.push("## Tool Calls");
    lines.push("");
    lines.push(`- **Total calls:** ${ctx.toolCalls.length}`);
    lines.push("");
    lines.push("## Generated Artifacts");
    lines.push("");
    if (ctx.artifacts.length === 0) {
      lines.push("_No artifacts generated._");
    } else {
      for (const a of ctx.artifacts) {
        lines.push(`- \`${a}\``);
      }
    }
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("_Generated by AEOS Kernel Runtime v0.1_");
    return lines.join("\n");
  }

  writePermissionDecisions(decisions: PermissionDecision[]): string {
    const lines: string[] = [];
    lines.push("# Permission Decisions");
    lines.push("");
    lines.push(`- **Total:** ${decisions.length}`);
    lines.push("");
    for (const d of decisions) {
      const icon = d.allowed ? "✅" : "❌";
      lines.push(`### ${icon} ${d.action}`);
      lines.push("");
      lines.push(`- **Agent:** ${d.agentId}`);
      lines.push(`- **Resource:** ${d.resource}`);
      lines.push(`- **Allowed:** ${d.allowed}`);
      lines.push(`- **Reason:** ${d.reason}`);
      lines.push(`- **Timestamp:** ${d.timestamp}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
    lines.push("_Default policy: deny-all_");
    return lines.join("\n");
  }
}
