<?php
if (!defined('ABSPATH')) { exit; }
get_header();
$theme_uri = get_stylesheet_directory_uri();
$products = reidoabc_gourmet_products();
?>
<main>
  <section class="hero-carousel-section" aria-label="Destaques Rei do ABC"><div class="carousel-container"><button class="carousel-arrow prev" type="button" aria-label="Slide anterior">&#8249;</button><button class="carousel-arrow next" type="button" aria-label="Próximo slide">&#8250;</button><div class="carousel-slide active" data-slide="1"><img src="<?php echo esc_url(reidoabc_get_hero_slide_1_url()); ?>" alt="Banner de destaque Rei do ABC" data-replacement-slot="assets/images/hero-slide-1-replacement.jpg"><div class="carousel-overlay"><h1>Barras de Chocolate Gourmet</h1><p>Seleção artesanal para momentos especiais.</p></div></div><div class="carousel-slide" data-slide="2"><img src="<?php echo esc_url(reidoabc_get_hero_slide_1_url()); ?>" alt="Pedaços de tortas gourmet"><div class="carousel-overlay"><h2>Pedaços de Tortas Selecionadas</h2><p>Receitas autorais, ingredientes nobres e acabamento cuidadoso.</p></div></div></div></section>
  <section class="feature-bar-section" aria-label="Diferenciais"><div class="feature-box"><div class="feature-text"><h2>Envio Rápido</h2><p>Para todo Brasil</p></div></div><div class="feature-box"><div class="feature-text"><h2>Food Service</h2><p>Produtos para experiências memoráveis.</p></div></div><div class="feature-box"><div class="feature-text"><h2>Pagamento Online</h2><p>Checkout seguro e pedido registrado.</p></div></div></section>
  <section class="products-section" id="produtos"><h2 class="section-pill-header">Produtos Populares</h2><?php if ($products) : ?><div class="product-grid"><?php foreach ($products as $product) : ?><article class="product-card"><a href="<?php echo esc_url($product->get_permalink()); ?>" class="product-card-image-link"><img src="<?php echo esc_url(reidoabc_gourmet_product_image_url($product)); ?>" alt="<?php echo esc_attr($product->get_name()); ?>" class="product-img" loading="lazy"></a><div><h3><a href="<?php echo esc_url($product->get_permalink()); ?>"><?php echo esc_html($product->get_name()); ?></a></h3></div><div><div class="price"><?php echo wp_kses_post($product->get_price_html()); ?></div><a href="<?php echo esc_url($product->add_to_cart_url()); ?>" class="btn-add-cart" data-product_id="<?php echo esc_attr((string) $product->get_id()); ?>">Adicionar ao carrinho</a></div></article><?php endforeach; ?></div><?php else : ?><p class="reidoabc-empty-products">Os produtos desta seleção serão cadastrados pelo painel WordPress.</p><?php endif; ?></section>
  <section class="delivery-row-section"><div class="delivery-row-grid"><article class="callout-card"><div><span class="tag">Loja Física</span><h2>Vem visitar nossa loja do Rei do ABC</h2><p>Muitos doces para você.</p></div><a href="https://maps.google.com" class="btn-callout" target="_blank" rel="noopener noreferrer">Saiba como chegar</a></article><article class="callout-card"><div><span class="tag">Delivery do Rei</span><h2>Faça seu pedido pelo Rei do ABC</h2><p>Todos nossos doces na sua mão.</p></div><a href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>" class="btn-callout">Conhecer a seleção</a></article></div></section>
</main>
<?php get_footer();
